all: help.html

help.html: help.rst
	rst2html --no-generator --language=pt_pt --config=help.config help.rst > help.html


# NOTE: Usually include the language (like this), but docutils does not support Portugese now...
#
#	rst2html --no-generator --language=pt --config=help.config help.rst > help.html

