; en-GB.plg_finder_attachments.ini
; Attachments for Joomla! extension
; Copyright (C) 2007-2026 Jonathan M. Cameron, All rights reserved.
; License https://www.gnu.org/licenses/gpl-3.0.html GNU/GPL
; Note : All ini files need to be saved as UTF-8 - No BOM

; German translation Thunnes (4.2.4)

ATTACH_ATTACHMENTS_FINDER_PLUGIN_DESCRIPTION="Das Attachments-Finder-Plugin ermöglicht die Suche in allen Dateinamen/URLs und Beschreibungen von Anhängen."
PLG_FINDER_QUERY_FILTER_BRANCH_P_ATTACHMENT="Anhänge"
PLG_FINDER_QUERY_FILTER_BRANCH_S_ATTACHMENT="Anhänge"
